---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luowei.
--- DateTime: 2019/8/18 10:59
---

logFileName = "system.log"

-- 查找日志中包含"executed. 44.848263 millis"的行数，并找到执行时间最长的那一行日志
logFile = io.open(logFileName)
local lineCnt = 0
local executeTime = 0
local maxExecuteTimeLine = 0
local maxExecuteTime = 0
local lineNumber = 1

startTime = os.clock();
for line in logFile:lines() do
    si, ei, executeTime = string.find(line, "executed%.%s*([%d.]+)%smillis")
    if si then
        lineCnt = lineCnt + 1
        if (tonumber(maxExecuteTime) < tonumber(executeTime)) then
            maxExecuteTime = executeTime
            maxExecuteTimeLine = lineNumber
        end

        -- 检查没有加supplier_id查询条件的
        si, ei = string.find(line, "supplier_id%s*=%s*%?");
        if si == nil then
            print("linNumber = " .. tostring(lineNumber), "executeTime = " .. tonumber(executeTime), " line = " .. tostring(line))
        end
    end
    lineNumber = lineNumber + 1

end
completeTime = os.clock();
diffTime = completeTime -  startTime
print("cost time = " .. diffTime)
print("包含 executed. 44.848263 millis 的行数 = " .. tostring(lineCnt), "maxExecuteTime = " .. tostring(maxExecuteTime), "maxExecuteTimeLine = " .. tostring(maxExecuteTimeLine))

