---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luowei.
--- DateTime: 2019/8/18 19:59
---
local persons = redis.call('hkeys', KEYS[1])
local totalScore = 0
local scores = redis.call('hmget', KEYS[1], unpack(persons))
for i, s in ipairs(scores) do
    totalScore = tonumber(totalScore) + tonumber(s)
end
local avgScore = totalScore / #scores
return avgScore