---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luowei.
--- DateTime: 2019/8/10 22:00
---
print("enter a number");
a = io.read("*number");

-- 定义一个阶乘函数
function fact(n)
    if n == 0 then
        return 1;
    else
        return n * fact(n - 1);
    end
end

print(fact(a))
-- print("fact(" + a + ")=" + fact(a))